import streamlit as st
import openai

st.set_page_config(page_title="Skilvyn Tutor", layout="wide")

# OpenAI API Key setup
if "OPENAI_API_KEY" not in st.secrets:
    st.error("Please set your OpenAI API key in Streamlit secrets.")
    st.stop()
openai.api_key = st.secrets["OPENAI_API_KEY"]

# Default session state
defaults = {
    "chat_history": [],
    "user_info": {},
    "skills": ["Prompt Engineering"],
    "selected_skill": None,
    "skill_level": None,
    "learning_path": [],
    "current_unit": 0,
    "unit_passed": False,
    "stage": "welcome"
}
for k, v in defaults.items():
    if k not in st.session_state:
        st.session_state[k] = v

def ai_chat(messages, temperature=0.7, max_tokens=256):
    try:
        resp = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens
        )
        return resp.choices[0].message.content.strip()
    except Exception as e:
        return None  # Return None to signal failure

def assistant_reply(user_input=None):
    history = st.session_state.chat_history.copy()
    if user_input:
        history.append({"role": "user", "content": user_input})
    reply = ai_chat(history)
    if reply is None:
        st.error("Sorry, there was an error communicating with the AI. Please try again later.")
        st.stop()
    history.append({"role": "assistant", "content": reply})
    st.session_state.chat_history = history
    return reply

def show_chat():
    for msg in st.session_state.chat_history:
        if msg["role"] == "assistant":
            st.chat_message("assistant").markdown(msg["content"])
        else:
            st.chat_message("user").markdown(msg["content"])

# --------- App Flow Logic ---------

if st.session_state.stage == "welcome":
    if not st.session_state.chat_history:
        welcome = ai_chat([
            {"role": "system", "content": "You are a friendly educational chatbot assistant. Speak English. Explain everything to the user, and clarify that all content is AI-generated."},
            {"role": "user", "content": "Welcome the user to Skilvyn, explain it is an interactive AI-powered learning platform. Make it clear that all content in this app is generated by AI."}
        ])
        if welcome is None:
            st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
            st.stop()
        st.session_state.chat_history.append({"role": "assistant", "content": welcome + "\nHow would you like me to call you?"})
    show_chat()
    user_input = st.chat_input("Enter your name or how you'd like to be addressed...")
    if user_input:
        st.session_state.user_info["name"] = user_input.strip()
        st.session_state.chat_history.append({"role": "user", "content": user_input})
        ask = ai_chat([
            {"role": "system", "content": "You are a friendly educational chatbot assistant. Speak English."},
            {"role": "user", "content": f"The user said their name is {user_input}. Politely ask them for their email address."}
        ])
        if ask is None:
            st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
            st.stop()
        st.session_state.chat_history.append({"role": "assistant", "content": ask})
        st.session_state.stage = "ask_info"
        st.experimental_rerun()
    st.stop()

elif st.session_state.stage == "ask_info":
    show_chat()
    user_input = st.chat_input("Enter your email address...")
    if user_input:
        st.session_state.user_info["email"] = user_input.strip()
        st.session_state.chat_history.append({"role": "user", "content": user_input})
        ask = ai_chat([
            {"role": "system", "content": "You are a friendly educational chatbot assistant. Speak English."},
            {"role": "user", "content": "Ask the user for their date of birth (format: YYYY-MM-DD) in a concise and polite way."}
        ])
        if ask is None:
            st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
            st.stop()
        st.session_state.chat_history.append({"role": "assistant", "content": ask})
        st.session_state.stage = "choose_skill"
        st.experimental_rerun()
    st.stop()

elif st.session_state.stage == "choose_skill":
    show_chat()
    user_input = st.chat_input("Enter your date of birth (e.g., 1990-01-01)...")
    if user_input:
        st.session_state.user_info["birth"] = user_input.strip()
        st.session_state.chat_history.append({"role": "user", "content": user_input})
        skills_message = ai_chat([
            {"role": "system", "content": "You are a friendly educational chatbot assistant. Speak English."},
            {"role": "user", "content": "Tell the user that currently only 'Prompt Engineering' is available to learn, and more skills will be added soon. Ask them to confirm if they want to start learning Prompt Engineering."}
        ])
        if skills_message is None:
            st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
            st.stop()
        st.session_state.chat_history.append({"role": "assistant", "content": skills_message})
        st.session_state.stage = "ask_level"
        st.experimental_rerun()
    st.stop()

elif st.session_state.stage == "ask_level":
    show_chat()
    user_input = st.chat_input("Would you like to learn Prompt Engineering? (yes/no)...")
    if user_input and "yes" in user_input.strip().lower():
        st.session_state.selected_skill = "Prompt Engineering"
        st.session_state.chat_history.append({"role": "user", "content": user_input})
        ask = ai_chat([
            {"role": "system", "content": "You are a friendly educational chatbot assistant. Speak English."},
            {"role": "user", "content": "Ask the user to briefly describe their current experience level in Prompt Engineering (beginner/intermediate/advanced or a short sentence about themselves)."}
        ])
        if ask is None:
            st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
            st.stop()
        st.session_state.chat_history.append({"role": "assistant", "content": ask})
        st.session_state.stage = "generate_path"
        st.experimental_rerun()
    elif user_input:
        st.session_state.chat_history.append({"role": "user", "content": user_input})
        sorry = ai_chat([
            {"role": "system", "content": "You are a friendly educational chatbot assistant. Speak English."},
            {"role": "user", "content": "Thank the user and let them know they can return later when more skills are added."}
        ])
        if sorry is None:
            st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
            st.stop()
        st.session_state.chat_history.append({"role": "assistant", "content": sorry})
        st.stop()
    st.stop()

elif st.session_state.stage == "generate_path":
    show_chat()
    user_input = st.chat_input("Describe your current experience...")
    if user_input:
        st.session_state.skill_level = user_input.strip()
        st.session_state.chat_history.append({"role": "user", "content": user_input})
        prompt = (
            f"You are an AI learning assistant for a student named {st.session_state.user_info['name']} who wants to learn Prompt Engineering. "
            f"Their experience: {st.session_state.skill_level}. Create a plan with 5 units, each with a short title, a learning objective, and a welcome message for the unit. "
            "Return the list as JSON with objects containing: title, objective, welcome."
        )
        plan = ai_chat([{"role": "system", "content": prompt}], temperature=0.5, max_tokens=512)
        if plan is None:
            st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
            st.stop()
        import json
        try:
            learning_path = json.loads(plan)
            st.session_state.learning_path = learning_path
            st.session_state.current_unit = 0
            st.session_state.stage = "in_unit"
            msg = ai_chat([
                {"role": "system", "content": "You are a friendly educational chatbot assistant. Speak English."},
                {"role": "user", "content": f"Welcome the user and inform them they are starting with the first unit: {learning_path[0]['title']}. Show the unit's welcome message."}
            ])
            if msg is None:
                st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
                st.stop()
            msg += f"\n\n{learning_path[0]['welcome']}"
            st.session_state.chat_history.append({"role": "assistant", "content": msg})
            st.experimental_rerun()
        except Exception:
            st.error("Sorry, there was an error processing the learning path. Please try again.")
            st.stop()
    st.stop()

elif st.session_state.stage == "in_unit":
    unit = st.session_state.learning_path[st.session_state.current_unit]
    show_chat()
    user_input = st.chat_input("Ask or answer via chat...")
    if user_input:
        st.session_state.chat_history.append({"role": "user", "content": user_input})
        tutor_prompt = [
            {"role": "system", "content": (
                f"You are a smart tutor. The unit: {unit['title']}. Unit objective: {unit['objective']}."
                " Evaluate the student's answer and respond. At the end, on a separate line, add: [status:pass] if ready for the next unit, or [status:stay] if not ready."
            )},
        ] + st.session_state.chat_history[-6:]
        reply = ai_chat(tutor_prompt)
        if reply is None:
            st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
            st.stop()
        st.session_state.chat_history.append({"role": "assistant", "content": reply})
        if "[status:pass]" in reply:
            if st.session_state.current_unit + 1 < len(st.session_state.learning_path):
                st.session_state.current_unit += 1
                next_unit = st.session_state.learning_path[st.session_state.current_unit]
                msg = ai_chat([
                    {"role": "system", "content": "You are a friendly educational chatbot assistant. Speak English."},
                    {"role": "user", "content": f"Let the user know they've moved to the next unit titled: {next_unit['title']}. Show the unit's welcome message."}
                ])
                if msg is None:
                    st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
                    st.stop()
                msg += f"\n\n{next_unit['welcome']}"
                st.session_state.chat_history.append({"role": "assistant", "content": msg})
            else:
                st.session_state.stage = "path_complete"
                st.session_state.chat_history.append({"role": "assistant", "content": "🎉 Congratulations! You have completed all units successfully."})
        elif "[status:stay]" in reply:
            encourage = ai_chat([
                {"role": "system", "content": "You are a friendly educational chatbot assistant. Speak English."},
                {"role": "user", "content": "Encourage the user to keep working on this unit until they're ready to move on."}
            ])
            if encourage is None:
                st.error("Sorry, there was an error communicating with the AI. Please reload the page later.")
                st.stop()
            st.session_state.chat_history.append({"role": "assistant", "content": encourage})
        st.experimental_rerun()
    st.stop()

elif st.session_state.stage == "path_complete":
    show_chat()
    st.success("You have completed the program! You can start over or review your units.")
    if st.button("Start Over"):
        for k in ("chat_history", "user_info", "selected_skill", "skill_level", "learning_path", "current_unit", "stage"):
            st.session_state[k] = defaults[k]
        st.experimental_rerun()
